### ISSUE TITLE
Disable filtering on profile pages

### ISSUE THREAD

**Issue by jgentes** [brocef/BetterSoundCloud#1]
@brocef thanks for creating this. Super userful for filtering the stream. 

However if I click on a user to see their profile / tracks, it would be nice if the plugin didn't filter their tracks, usually because I've found a new artist and I want to listen to some of their music.

Just a thought, I think it would be a url comparison for /stream vs /anything-else.

**Comment by brocef** [comment]
Good idea. I'll add an option for that.

**Comment by brocef** [comment]
Okay, this has been added in v1.1.0 as a new option, "Only Filter Stream" and it works as you essentially describe by checking the current URL.

It should be live in about a half-hour.

I'm marking this closed, as it is a feature request. If there are any issues/bugs with the new version, feel free to open up a new issue here. Thank you for your suggestion and support!
