### ISSUE TITLE
Repost Blacklist by User

### ISSUE THREAD

**Issue by camjac251** [brocef/BetterSoundCloud#2]
Would it be possible to have a blacklist of reposts. Like if you only want to block reposts from certain users while keeping them turned on for others you follow?

**Comment by brocef** [comment]
Certainly possible. I'll look into this.

**Comment by brocef** [comment]
I've implemented this as a feature in 1.2.0. There is one limitation currently that I'm working on, which is that once you block a user, the changes to your feed won't take effect until you refresh the page. Hopefully I'll get real-time repost blocking implemented soon.

Please give it a test and let me know if there are any bugs or concerns.

**Comment by camjac251** [comment]
I use Firefox as my main web browser. Is this addon compatible with webextensions, allowing firefox compilation?

Also, thank you for adding this cool feature. Reposts are great now :)

**Comment by brocef** [comment]
No, I have not written an equivalent Firefox extension. Perhaps one day.
