### ISSUE TITLE
Extension no longer working

### ISSUE THREAD

**Issue by kbeeveer46** [brocef/BetterSoundCloud#4]
I've been using this extension for a few months and all the sudden it stopped working this past week. It no longer says it's "running" at the top of the page on Soundcloud. I've tried un-installing and installing it both in Opera and Chrome without any luck.

**Comment by bcefali-vidaid** [comment]
Hi, thank you for letting me know. I'll check it out early this week.

**Comment by bcefali-vidaid** [comment]
Okay @kbeeveer46 , I fixed it. There seems to be an unrelated issue regarding hiding/showing filtered tracks, but the extension should work again for the most part. It may take a bit for Google to push v1.2.2 to the store, so wait an hour or so before checking.

**Comment by kbeeveer46** [comment]
@bcefali-vidaid Thanks! Works for me after getting the new version.
