### ISSUE TITLE
How to install as Chrome Extension?

### ISSUE THREAD

**Issue by boldib** [brocef/BetterSoundCloud#6]
Hi,

I do not find it anymore at the chrome's extension webstore. 

Could you help please, how is it possible to install it to chrome?

Thank you!

**Comment by brocef** [comment]
Hi,

Regretfully, Google removed my extension from the web store at SoundCloud's request. You can still use this extension but you will need to install it manually.

Download this repository then go to chrome://extensions, and then turn on Developer mode (top-right of the page). Once that is on, you can load an unpacked extension. Click that and then select the public_html folder from this repository and it will load BSC.
